repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.4
    hooks:
      - id: golangci-lint
        args:
          [
            '--fix',
            '--timeout=5m',
            '--config=.golangci.yml',
            './cmd/...',
            './pkg/...',
            './service/...',
          ]
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        files: ^go\.mod$

      - id: go-test
        name: Run Go tests
        entry: go test ./... -v
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: generate-docs
        name: Generate documentation
        entry: go run scripts/gendocs.go
        language: system
        files: ^(pkg/|cmd/|service/|docs/)
        pass_filenames: false
        stages: [pre-commit]

      - id: branch-name-validation
        name: Branch name validation
        entry: ./scripts/validate-branch-name.sh
        language: system
        pass_filenames: false
        stages: [pre-push, pre-commit]
        always_run: true
        require_serial: true
        verbose: true
        env:
          CI: ${CI}
          GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
          GITHUB_REF: ${GITHUB_REF}

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
