version: string # v1
kind: string # NixConfig
type: string # user|team|project
metadata:
  name: string
  description: string
  created: timestamp
  updated: timestamp
  priority?: number # Higher priority configs override lower priority ones
base?: string # Name of the config to extend from
settings:
  shell: string # bash|zsh|fish
  logLevel: string # info|debug|warn|error
  autoUpdate: boolean
  updateInterval: duration # e.g., 24h
nix:
  manager: string # nix-env
  packages:
    core?: [string] # Required for team/project configs, not for user configs
    optional?: [string] # Optional packages
  scripts?:
    - name: string
      description?: string
      commands: string # Multiline string with | style
