version: string # v1
kind: string # NixConfig
metadata:
  name: string
  description: string
  created: timestamp
  updated: timestamp
settings:
  shell: string # bash|zsh|fish
  logLevel: string # info|debug|warn|error
  autoUpdate: boolean
  updateInterval: duration # e.g., 24h
nix:
  manager: string # nix-env
  packages:
    core: [string] # Required, non-empty
    optional?: [string] # Optional packages
  scripts?:
    - name: string
      description?: string
      commands: string # Multiline string with | style
