{ config, pkgs, lib, ... }:

{
  options = {};

  config = {
    xdg.configFile."zsh/.p10k.zsh".text = ''
      # Generated by Powerlevel10k configuration wizard
      () {
        emulate -L zsh -o extended_glob

        # Unset all configuration options
        unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

        # Left prompt segments
        typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
          os_icon                 # os identifier
          dir                     # current directory
          vcs                     # git status
          newline                # \n
          prompt_char            # prompt symbol
        )

        # Right prompt segments
        typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
          status                  # exit code of the last command
          command_execution_time  # duration of the last command
          background_jobs        # presence of background jobs
          direnv                 # direnv status
          nix_shell            # nix shell
          time                 # current time
        )

        # Mode and icons
        typeset -g POWERLEVEL9K_MODE=nerdfont-complete
      }

      # Tell p10k configure which file it should overwrite
      typeset -g POWERLEVEL9K_CONFIG_FILE=''${ZDOTDIR}/.p10k.zsh
    '';
  };
}
