name: Check Release Flag
on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
    outputs:
      should_publish:
        description: "Whether a release should be published"
        value: ${{ jobs.check_flag.outputs.should_publish }}
      release_type:
        description: "Type of release (major/minor/patch)"
        value: ${{ jobs.check_flag.outputs.release_type }}
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check_flag:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      should_publish: ${{ steps.check-version.outputs.should_publish }}
      release_type: ${{ steps.check-version.outputs.release_type }}
    steps:
      - name: Check Release Flag
        id: check-version
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env.PR_NUMBER || context.payload.pull_request.number
            });

            let releaseType = '';
            const labels = pr.data.labels.map(l => l.name);
            const title = pr.data.title.toLowerCase();
            const body = pr.data.body || '';

            // Valid scopes from commitlint config
            const validScopes = ['api', 'deps', 'mod'];
            const scopePattern = new RegExp(`^(feat|fix)\\((${validScopes.join('|')})\\)!?:`);

            // Check for breaking changes
            if (
              labels.includes('major') ||
              title.match(/^(feat|fix)!:/) ||
              title.match(new RegExp(`^(feat|fix)\\((${validScopes.join('|')})\\)!:`)) ||
              body.includes('BREAKING CHANGE:')
            ) {
              releaseType = 'major';
            }
            // Check for features (minor)
            else if (
              labels.includes('minor') ||
              title.startsWith('feat:') ||
              title.match(/^feat\([^)]+\):/)
            ) {
              releaseType = 'minor';
            }
            // Check for patches
            else if (
              labels.includes('patch') ||
              title.startsWith('fix:') ||
              title.match(/^fix\([^)]+\):/) ||
              title.startsWith('perf:') ||
              title.match(/^perf\([^)]+\):/) ||
              title.startsWith('refactor:') ||
              title.match(/^refactor\([^)]+\):/) ||
              title.startsWith('build:') ||
              title.match(/^build\([^)]+\):/) ||
              title.startsWith('deps:') ||
              title.match(/^deps\([^)]+\):/) ||
              title.startsWith('go:') ||
              title.match(/^go\([^)]+\):/)
            ) {
              releaseType = 'patch';
            }

            const shouldPublish = releaseType ? 'true' : 'false';
            core.setOutput('should_publish', shouldPublish);
            core.setOutput('release_type', releaseType);
            return { shouldPublish, releaseType };

      - name: Comment on PR if no release flag
        if: steps.check-version.outputs.should_publish != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const body = `No release flag detected. To trigger a release, use one of these methods:

            1. Add a label:
               - \`major\` - Breaking changes
               - \`minor\` - New features
               - \`patch\` - Bug fixes and improvements

            2. Use conventional commit format in PR title:

            Major version (Breaking changes):
            - \`feat!: change configuration file format\`
            - \`feat(api)!: change API response format\`
            - \`fix!: remove deprecated function\`
            - Or include \`BREAKING CHANGE:\` in the PR description

            Minor version (Features):
            - \`feat: add new command\`
            - \`feat(api): add new endpoint\`

            Patch version:
            - \`fix: resolve config parsing issue\`
            - \`fix(api): fix endpoint response\`
            - \`perf: improve build speed\`
            - \`refactor: restructure command handling\`
            - \`build: update build system\`
            - \`deps: update dependencies\`
            - \`go: update Go version\`
            - \`go(mod): update module dependencies\`

            No version bump:
            - \`style: format code\`
            - \`test: add new tests\`
            - \`ci: update workflows\`
            - \`docs: update readme\`

            Valid scopes: api, deps, mod

            Note: All commit messages must follow the conventional commit format and use approved scopes.`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER || context.issue.number,
              per_page: 1,
              page: 1
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('No release flag detected')
            );

            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: process.env.PR_NUMBER || context.issue.number,
                body: body
              });
            }
        env:
          PR_NUMBER: ${{ inputs.pull_request_number }}
