name: Check Release Flag
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check_flag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Release Flag
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.data.head.sha
            });

            const commitMessage = commit.data.commit.message;
            console.log('Commit message:', commitMessage);

            let releaseType = '';

            if (commitMessage.startsWith('feat!:') || commitMessage.startsWith('fix!:') || commitMessage.includes('BREAKING CHANGE:')) {
              releaseType = 'major';
            } else if (commitMessage.startsWith('feat:')) {
              releaseType = 'minor';
            } else if (commitMessage.startsWith('fix:') || commitMessage.startsWith('perf:') || commitMessage.startsWith('refactor:') || commitMessage.startsWith('build:') || commitMessage.startsWith('deps:') || commitMessage.startsWith('go:')) {
              releaseType = 'patch';
            }

            const shouldPublish = releaseType ? 'true' : 'false';
            core.setOutput('should_publish', shouldPublish);
            core.setOutput('release_type', releaseType);
