name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.22']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go mod download

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m

    - name: Run golangci-lint
      run: golangci-lint run --out-format=colored-line-number

    - name: Run tests
      run: go test -v ./...

  docs:
    name: Verify Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Generate docs in a temporary directory
      run: |
        # Create temp directory structure
        mkdir -p /tmp/docs/commands

        # Copy non-command docs
        find docs -maxdepth 1 -type f -exec cp {} /tmp/docs/ \;

        # Copy command docs
        cp -r docs/commands/* /tmp/docs/commands/

        # Generate new docs
        go run scripts/gendocs.go

        # Compare non-command docs
        if ! diff -r --exclude=commands docs/ /tmp/docs/; then
          echo "Error: Generated non-command docs differ from committed docs."
          echo "Please run 'go run scripts/gendocs.go' locally and commit the changes."
          exit 1
        fi

        # Compare command docs ignoring date lines
        for file in docs/commands/*.md; do
          basename=$(basename "$file")
          if ! diff -I "Auto generated by spf13/cobra on" "$file" "/tmp/docs/commands/$basename"; then
            echo "Error: Generated command docs differ from committed docs (ignoring dates)."
            echo "Please run 'go run scripts/gendocs.go' locally and commit the changes."
            exit 1
          fi
        done
