name: Release Management

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git checkout -b beta
          fi

      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Beta Comment
        if: github.event_name == 'pull_request' && steps.semantic.outputs.new_release_published == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ steps.semantic.outputs.new_release_version }}'
            const downloadUrl = `https://github.com/${{ github.repository }}/releases/download/${version}/nix-foundry-\$(uname -s | tr '[:upper:]' '[:lower:]')-\$(uname -m)`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Beta release ${version} ready for testing:

              **Installation Command:**
              \`\`\`bash
              curl -L ${downloadUrl} -o nix-foundry && chmod +x nix-foundry
              \`\`\`

              ${{ steps.semantic.outputs.new_release_notes }}`
            })
