name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install pre-commit
        run: nix-shell -p pre-commit nixpkgs-fmt --run "pre-commit install"

      - name: Fix file formatting
        run: |
          nix-shell -p pre-commit nixpkgs-fmt --run "pre-commit run trailing-whitespace --all-files || true"
          nix-shell -p pre-commit nixpkgs-fmt --run "pre-commit run end-of-file-fixer --all-files || true"
          nix-shell -p pre-commit nixpkgs-fmt --run "pre-commit run nixpkgs-fmt --all-files || true"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "style: fix formatting" || true

      - name: Run pre-commit checks
        run: nix-shell -p pre-commit nixpkgs-fmt --run "pre-commit run --all-files"

  build:
    name: Test on ${{ matrix.os }}
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: x86_64-linux
          - os: macos-14
            platform: aarch64-darwin
          - os: macos-13
            platform: x86_64-darwin

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Test flake builds
      run: |
        export NIX_USER=$USER
        export HOST=$(hostname)

        mkdir -p ~/.config/nix
        echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

        nix flake check
        if [[ "${{ matrix.platform }}" == *"-darwin" ]]; then
          nix build ".#darwinConfigurations.default.system" --system ${{ matrix.platform }}
        else
          nix build ".#homeConfigurations.default.activationPackage" --system ${{ matrix.platform }}
        fi
